---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: add odoo apt-key
      apt_key:
        url: https://nightly.odoo.com/odoo.key
        state: present

    - name: Add odoo repo
      apt_repository:
        repo: 'deb http://nightly.odoo.com/15.0/nightly/deb/ ./'
        state: present

    - name: Install wkhtmltopdf
      apt:
        deb: https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.focal_amd64.deb
        state: present

    - name: Update debian linux and install odoo
      apt:
        name: odoo
        update_cache: yes
        # upgrade: yes

    - name: Enable odoo service
      service:
        name: odoo
        enabled: yes
        state: started

    - name: Configure odoo
      template:
        src: templates/odoo_config.conf.j2
        dest: /etc/odoo/odoo.conf
      notify: restart odoo

    - name: Open odoo port
      ufw:
        state: enabled
        port: 8069,ssh
        policy: allow
        proto: tcp

    - debug: var=hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address']

  handlers:
    - name: restart odoo
      service:
        name: odoo
        state: restarted

      