---
- hosts: postgres
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Add postgresql repo apt-key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgresql apt-repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main
        state: present

    - name: Install prerequisite packages
      apt:
        name:
          - gnupg
          - gnupg2
          - bash
          - acl
        state: present
        update_cache: true

    - name: Install postgres packages
      apt:
        name: 
          - "postgresql-{{postgres_version}}"
          - python3-psycopg2
        state: latest

    - name: Create an odoo database
      postgresql_db:
        name: "{{ odoo_default_db }}"
        template: template0
        encoding: UTF8
        state: present
      become_user: postgres

    - name: Create an odoo user
      postgresql_user:
        name: "{{ odoo_user_db }}"
        password: "{{ odoo_password_db }}"
        db: "{{ odoo_default_db }}"
        priv: ALL
        state: present
      become_user: postgres

    - name: Grant user odoo from all network to database
      become_user: postgres
      postgresql_pg_hba:
        dest: "/etc/postgresql/{{postgres_version}}/main/pg_hba.conf"
        contype: host
        users: all
        source: "{{ db_allowed_networks }}"
        databases: all
        method: trust
      notify: restart postgres

    - name: Edit postgresql.conf
      lineinfile:
        path: "/etc/postgresql/{{postgres_version}}/main/postgresql.conf"
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"
        create: yes
      notify: restart postgres

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted
        enabled: yes